// Generated by https://quicktype.io

export interface Deaths {
  match_id: number;
  player_slot: number;
  radiant_win: boolean;
  duration: number;
  game_mode: number;
  lobby_type: number;
  deaths: number;
  hero_id: number;
  start_time: number;
  version: number | null;
  kills: number;
  assists: number;
  skill: number | null;
  leaver_status: number;
  party_size: number | null;
}
