// Generated by https://quicktype.io

export interface Shade {
  number: string;
  language: string;
  insult: string;
  created: string;
  shown: string;
  createdby: string;
  active: string;
  comment: string;
}
